### ISSUE TITLE
Chat translate switch to English

### ISSUE THREAD

**Issue by Akhtar1997** [aws-samples/amazon-connect-chat-translate#14]
We are using Aws translation feature on our instance , it detects language automatically and we want to know how we can fix the language once the conversation starts so that in between if the user type any message which means same in English the translation won't switch to English.

**Comment by ejferr** [comment]
Made multiple updates to the repository on Friday 3/29/2024. Can you please test and advise if your issue persists? If so, can you please send some examples of messages that "means the same in English" along with the original language?

**Comment by Akhtar1997** [comment]
@ejferr after the changes lot of issue we are facing like chat translate is not working, and i am not able to send chat through translate div to customer side.

**Comment by Akhtar1997** [comment]
@ejferr You can check the error ,i have attached in below
![WhatsApp Image 2024-04-02 at 11 12 31 AM](https://github.com/aws-samples/amazon-connect-chat-translate/assets/92727977/67f1ca6d-448b-48d0-9cf3-2bbfad8d222d)
![WhatsApp Image 2024-04-02 at 11 12 18 AM](https://github.com/aws-samples/amazon-connect-chat-translate/assets/92727977/69a7b335-c36d-402f-9885-df8ec9194ee9)

**Comment by ejferr** [comment]
Please pull the latest version. Issue is fixed. Please confirm

**Comment by Akhtar1997** [comment]
@ejferr everything is working fine.

**Comment by Akhtar1997** [comment]
@ejferr thanks, Now translated is working properly and message send to customer

**Comment by ejferr** [comment]
Thank you for the update. So sorry that this took so long to reconcile for you

**Comment by Akhtar1997** [comment]
@ejferr Hello Now we are facing same issue, Translated chat is not send to customer side, I have attached the screenshot in below.

![image](https://github.com/aws-samples/amazon-connect-chat-translate/assets/92727977/559d793f-d1de-4de6-a417-0d196bf2cbb0)
![image](https://github.com/aws-samples/amazon-connect-chat-translate/assets/92727977/15389226-46d8-417b-aeb2-c6ea98982f63)
