### ISSUE TITLE
Translation only working from customer to agent

### ISSUE THREAD

**Issue by OtherwisePrickly** [aws-samples/amazon-connect-chat-translate#45]
Hello, I've got the translate app set up in AWS Amplify however translation only seems to work inbound i.e. from the customer. When I enter a response in the translate window, it displays the message but without translation:

![image](https://github.com/aws-samples/amazon-connect-chat-translate/assets/30972845/146a5794-250e-4477-9688-8b9bcd0c6c1d)

**Comment by OtherwisePrickly** [comment]
Thanks for the quick response. I've updated the app and all working fine now 👍🏻

**Comment by ejferr** [comment]
Confirmed resolved
